name: cicd
on: push

jobs:
  test-api:

    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install boto3
        python -m pip install flake8 pytest
    - name: Run test-get
      run:  cd cloud-resume-challenge/tests && python -m pytest -v test_get.py
    - name: Run test-put
      run: cd cloud-resume-challenge/put-function && python -m pytest -v test_put.py