name: main
on: push

jobs:
  test-api:

    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run test-get
      run: cd cloud-resume-challenge/get-function && pytest app.py
    - name: Run test-put
      run: cd cloud-resume-challenge/put-function && pytest app.py
